site_name: Fabula Nova Crystallis Modding Wiki

theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: indigo    
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo.png

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LR-Research-Team
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xwCHwRc4zU

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - CLB scripting:
    - script/index.md
    - Getting started:
      - Setting up the codebase: script/basics/extracting.md
      - Setting up IntelliJ IDEA : script/basics/setup-intellij.md
      - Setting up VS Code : script/basics/setup-vscode.md
      - Setting up the exporter: script/basics/repacking.md
    - Writing scripts:
      - Examples: script/writing/examples.md
      - Tips: script/writing/tips.md
      - API: 
        - script/writing/api.md
        - FINAL FANTASY XIII: script/writing/api-xiii.md
        - FINAL FANTASY XIII-2: script/writing/api-xiii2.md
        - LIGHTNING RETURNS FINAL FANTASY XIII: script/writing/api-lr.md  
      - FAQ: script/writing/faq.md  
  - File formats:
    - file-formats/index.md
    - Archive Formats:
      - White BIN files: file-formats/archive-formats/white-bin.md
      - WPD Pack files: file-formats/archive-formats/wpd-pack.md
    - Animation Formats:
      - MCB: file-formats/animation-formats/mcb.md
      - MTB: file-formats/animation-formats/mtb.md
    - Audio Format:
      - SCD: file-formats/audio-format/scd.md
    - Database Format:
      - WDB: file-formats/database-format/wdb.md
      - WDB Contents: file-formats/database-format/wdb-contents.md
      - WDB Field Names: file-formats/database-format/wdb-field-names.md
    - Map Format:
      - LYB: file-formats/map-format/lyb.md
    - Model/Texture Formats:
      - TRB: file-formats/model-texture-formats/trb.md
      - IMGB: file-formats/model-texture-formats/imgb.md
    - Text Format:
      - ZTR: file-formats/text-format/ztr.md
      - Encoding Keys Info: file-formats/text-format/encoding-keys-info.md
      - Encoding Keys Common: file-formats/text-format/encoding-keys-common.md
      - Encoding Keys XIII: file-formats/text-format/encoding-keys-xiii.md
      - Encoding Keys XIII-2: file-formats/text-format/encoding-keys-xiii2.md
      - Encoding Keys LR: file-formats/text-format/encoding-keys-lr.md
    - Script Format:
      - CLB: file-formats/script-format/clb.md
    - Save Format:
      - DAT:  file-formats/save-format/dat.md
  - User Guide:
    - user-guide/index.md
    - Setting up Nova: user-guide/setting-up-nova.md
    - Installing Mods: user-guide/installing-mods.md
    - Importing Custom BGM with looping: user-guide/importing-bgm-with-looping.md
  - User Resource:
    - user-resource/index.md
    - Additional Tools: user-resource/additional-tools.md
    - Directory Info: user-resource/dirs-info.md
    - File IDs: user-resource/file-ids.md
    - File Info: user-resource/file-info.md
    - Zone Info: user-resource/zone-info.md